services:

  backend:
    build:
      context: ./backend
    container_name: pitsense_backend

    ports:
      - "8000:8000"

    volumes:
      - .:/app

  frontend:
  build:
    context: .
    dockerfile: frontend/Dockerfile
  container_name: pitsense_frontend
  ports:
    - "8501:8501"
  volumes:
    - .:/app
  depends_on:
    - backend